### PR TITLE
Fixed issue #44 and crashes on connection errors.

### PR DESCRIPTION
**Pull request by AnonymouX47**
- Reduced number of requests sent (actually just fixed issue #44).
  - Note that it's possible for ads to be played when the user skips a track.
- Fixed crashes on connection errors.
- Tested and works on both Windows and Linux.

### CODE REVIEW

**Comment by daspartho** [comment]
Since there is a possibility of Ad playing if user skips tracks, What you guys think should we implement this?

**Comment by AnonymouX47** [comment]
Hmm... true, it needs some thought.

Is there any other potential solution? :thinking_face:

**Comment by AnonymouX47** [comment]
I guess i should've left the separate PR for connectoon errors open.

**Comment by AnonymouX47** [comment]
I figured out a temporary but workable fix for the exception of skipping tracks.

A keyboard interrupt (`Ctrl-C`) can be sent to the program to trigger a dialogue that asks if the user wants to skip a track or exit the program.
If the user chooses to skip a track... the program sends the appropriate key signal to automatically do that.

This way, the script handles skipping tracks, hence it can simply go ahead to wait for the new track :)

@daspartho what do you think?

**Comment by AnonymouX47** [comment]
@daspartho I'll merge this PR now because the script currently is in a completely broken state and then implement the fix above soon.

See issue #52.

**Pull request merged**
