### PR TITLE
Wrong variable is used for path.

### PR DESCRIPTION
**Pull request by lykkjur**
Change the `PATH` variable used near the bottom to the proper `path` variable, which is assigned to the actual Spotify path earlier, which should fixing #26 and the other issues recorded in that thread.

### CODE REVIEW

**Comment by lykkjur** [comment]
o7b2b35 also incorporates #25

**Review by jobveldhuis — APPROVED** [review]
Looks good to me.

**Comment by AnonymouX47** [comment]
I think using `os,name` for Windows would be better since `sys.platform` could either be "win32" or "cygwin", depending on what console/shell from which the script is being run.

**Comment by lykkjur** [comment]
@AnonymouX47 that's a good point. Fixed it ce66ae4.

**Comment by AnonymouX47** [comment]
I see no wrong variable name and the platform dependent code has been handled in #29.
👍🏾

**Pull request closed without merging**
