### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WarpWing**
Fixed stupid typo

### CODE REVIEW

**Comment by AnonymouX47** [comment]
Check line 49 also `Spotifyy` -> `Spotify`.

**Comment by airD173** [comment]
One thing that bugs me is "SBA(SpotiByeAds)" missing a space. It should be "SBA (SpotiByeAds)"

**Comment by WarpWing** [comment]
> One thing that bugs me is "SBA(SpotiByeAds)" missing a space. It should be "SBA (SpotiByeAds)"

Understandable, let me fix that real quick!


> Check line 49 also: `Spotifyy` -> `Spotify`.

Woops, thanks for bringing it to my attention!

**Comment by WarpWing** [comment]
Fixed minor issues.

**Pull request merged**
