### PR TITLE
WIP Readme.md

### PR DESCRIPTION
**Pull request by WarpWing**
I made an improved README.md which includes the more in-depth instructions from #32. It's still WIP and still in the feedback stage. That is if we still need it, I still wrote it as a quick and dirty alternative to those who don't want to go to a separate webpage and scroll through the docs(No offense or anything to the person who made the read the docs, I just know it might be for some more.. lazier people.) Anyways, let me know what you guys think. Not my best work but I think it's alright for now. I still need to write improved instructions since credentials are now stored in a JSON file(optionally) and all that. Still need to keep up with the PRs!

### CODE REVIEW

**Comment by airD173** [comment]
The shields.io badges are quite cool. One thing I'll point out is that you say to run `cd SpotiByeAds.py`, when it should be `cd SpotiByeAds`. I believe that was the cause for issue #4.

**Comment by daspartho** [comment]
Really good README. I would just suggest to add the documentation section back as its really goes into details for newbies.

All in all Excellent work!

**Comment by daspartho** [comment]
Really good README, explains the projects really well. Excellent work man!

**Comment by WarpWing** [comment]
> The shields.io badges are quite cool. One thing I'll point out is that you say to run `cd SpotiByeAds.py`, when it should be `cd SpotiByeAds`. I believe that was the cause for issue #4.

Oh my bad lmao. Weird little typo, let me fix that

**Comment by WarpWing** [comment]
> Really good README, explains the projects really well. Excellent work man!

Thanks! I want to include a whole bunch more. Excited to see where this project goes :D

**Pull request merged**
