### PR TITLE
Use `sys.platform` instead of `os.name` #23

### LINKED ISSUE #21: Issues with manjaro
When running on manjaro the program doesn't close spotify. It still opens a new window tho. There for ads aren't skipped.
Specs:
```
OS: Manjaro Linux x86_64 
Kernel: 5.10.53-1-MANJARO 
Shell: bash 5.1.8 
WM: i3 
Terminal: kitty 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1660 
Memory: 2875MiB / 15990MiB 
```

### PR DESCRIPTION
**Pull request by michaeljgallagher**
Use `sys.platform` instead of `os.name` (#23). Potentially fixes #21 as well, but have not tested this.

### CODE REVIEW

**Review by lykkjur — APPROVED** [review]
Looks good to me 👍

**Comment by import-brain** [comment]
Would it be better to use sys.platform.startswith instead of sys.platform? It's just in case people are running this on older versions of python or Linux (Linux used to have sys.platform return linux8 or something like that)

**Comment by ceceba223** [comment]
Right now this PR doesn't seem to solve #21

**Comment by AnonymouX47** [comment]
The issue has been fixed by #29.

@ceceba223 as for the Manjaro case, see #21.

**Pull request closed without merging**
