### PR TITLE
Major/Minor fixes, add support for MacOS, ease-of-use enhancements

### PR DESCRIPTION
**Pull request by lykkjur**
This incorporates changes from #3 #7, #8 and #9, and fixes #6. It also:

- Adds support for MacOS devices running M1 Apple Silicon processors (Intel should work too?).
- Changes `ClientID`, `Client Secret`, and `username` variables to ask the user for input.
- Adds proper support for a MacOS package for ease of use for less knowledgable (or more lazy) folks. I can't add or create a release so @daspartho will need to do that (I can build the binary if you want though).
- Probably something else I'm blanking on.

### CODE REVIEW

**Review by WarpWing — APPROVED** [review]
Yeah this looks pretty good :D. Great work!

**Comment by The-Glit-ch** [comment]
Nice job on integrating most of the PRs 👍

**Comment by lykkjur** [comment]
bdc16c0 now incorporates #13 to, allowing the user to optionally save their credentials to a human-readable JSON.

**Comment by daspartho** [comment]
Great job! Integerated most PRs :D

**Pull request merged**
